const foodItem = [
  {
    id: 1,
    name: "Phở Bò",
    category: "phở",
    rating: 4.3,
    price: 13,
    img: "img/Pho/PhoBo.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "Phở Bò Gân",
    category: "phở",
    rating: 4.3,
    price: 15,
    img: "img/Pho/PhoBoGan.png",
    quantity: 1,
  },
  {
    id: 3,
    name: "Phở Bò Viên",
    category: "phở",
    rating: 4.3,
    price: 18,
    img: "img/Pho/PhoBoVien.png",
    quantity: 1,
  },
  {
    id: 4,
    name: "Phở Gà",
    category: "phở",
    rating: 4.3,
    price: 15,
    img: "img/Pho/PhoGa.png",
    quantity: 1,
  },
  {
    id: 5,
    name: "Phở Heo",
    category: "phở",
    rating: 4.3,
    price: 10,
    img: "img/Pho/PhoHeo.png",
    quantity: 1,
  },
  {
    id: 6,
    name: "Phở Tái Nạm",
    category: "phở",
    rating: 4.3,
    price: 12,
    img: "img/Pho/PhoTaiNam.png",
    quantity: 1,
  },
  // {
  //   id: 7,
  //   name: "Kashmiri Pho",
  //   category: "phở",
  //   rating: 4.3,
  //   price: 13,
  //   img: "img/Pho/kashmiri.pulao.png",
  //   quantity: 1,
  // },
  // {
  //   id: 8,
  //   name: "Memoni Pho",
  //   category: "phở",
  //   rating: 4.3,
  //   price: 20,
  //   img: "img/Pho/memoniPho.png",
  //   quantity: 1,
  // },
  // {
  //   id: 9,
  //   name: "Mughlai Pho",
  //   category: "phở",
  //   rating: 4.3,
  //   price: 15,
  //   img: "img/Pho/mughlai-Pho.png",
  //   quantity: 1,
  // },

  // Cơm
  {
    id: 10,
    name: "Cơm bò bít tết",
    category: "cơm",
    rating: 4.3,
    price: 11,
    img: "img/Com/ComBoBitTet.png",
    quantity: 1,
  },
  {
    id: 11,
    name: "Cơm Cà Ri",
    category: "cơm",
    rating: 4.3,
    price: 10,
    img: "img/Com/ComCaRi.png",
    quantity: 1,
  },
  {
    id: 12,
    name: "Cơm Chiên Dương Châu",
    category: "cơm",
    rating: 4.3,
    price: 14,
    img: "img/Com/ComChienDuongChau.png",
    quantity: 1,
  },
  {
    id: 13,
    name: "Cơm Gà Xối Mỡ",
    category: "cơm",
    rating: 4.3,
    price: 12,
    img: "img/Com/ComGaXoiMo.png",
    quantity: 1,
  },
  {
    id: 14,
    name: "Cơm Sườn",
    category: "cơm",
    rating: 4.3,
    price: 17,
    img: "img/Com/ComSuon.png",
    quantity: 1,
  },
  {
    id: 15,
    name: "Cơm Xá Xíu",
    category: "cơm",
    rating: 4.3,
    price: 20,
    img: "img/Com/ComXaXiu.png",
    quantity: 1,
  },
  {
    id: 16,
    name: "Matar Paneer",
    category: "paneer",
    rating: 4.3,
    price: 15,
    img: "img/paneer/Matar-Paneer.png",
    quantity: 1,
  },
  {
    id: 17,
    name: "Palak Paneer",
    category: "paneer",
    rating: 4.3,
    price: 10,
    img: "img/paneer/palak-paneer.png",
    quantity: 1,
  },
  {
    id: 18,
    name: "Paneer Butter Masala",
    category: "paneer",
    rating: 4.3,
    price: 15,
    img: "img/paneer/paneer-butter-masala.png",
    quantity: 1,
  },
  {
    id: 19,
    name: "Paneer Do Pyaza",
    category: "paneer",
    rating: 4.3,
    price: 12,
    img: "img/paneer/Paneer-Do-Pyaza.png",
    quantity: 1,
  },
  {
    id: 20,
    name: "Hyderabadi Paneer",
    category: "paneer",
    rating: 4.3,
    price: 8,
    img: "img/paneer/Paneer-Hyderabadi.png",
    quantity: 1,
  },
  {
    id: 21,
    name: "Paneer Lababdar",
    category: "paneer",
    rating: 4.3,
    price: 7,
    img: "img/paneer/paneer-lababdar.png",
    quantity: 1,
  },
  {
    id: 22,
    name: "Shahi Paneer",
    age: "32",
    category: "paneer",
    rating: 4.3,
    price: 5,
    img: "img/paneer/shahi-paneer.png",
    quantity: 1,
  },
  {
    id: 23,
    name: "Navratan Korma",
    category: "vegetable",
    rating: 4.3,
    price: 8,
    img: "img/vegetable/navratan-korma_-vegetable.png",
    quantity: 1,
  },
  {
    id: 24,
    name: "Veg Jalfrezi",
    category: "vegetable",
    rating: 4.3,
    price: 7,
    img: "img/vegetable/VEG-JALFREZI.png",
    quantity: 1,
  },
  {
    id: 25,
    name: "Veg Pho",
    category: "vegetable",
    rating: 4.3,
    price: 5,
    img: "img/vegetable/vegetable-Pho.png",
    quantity: 1,
  },
  {
    id: 26,
    name: "Veg Curry",
    category: "vegetable",
    rating: 4.3,
    price: 7,
    img: "img/vegetable/vegetable-curry.jpeg",
    quantity: 1,
  },
  {
    id: 27,
    name: "Veg Kolhapur",
    category: "vegetable",
    rating: 4.3,
    price: 10,
    img: "img/vegetable/vegetable-kolhapuri.png",
    quantity: 1,
  },
  {
    id: 28,
    name: "Veg Masala",
    category: "vegetable",
    rating: 4.3,
    price: 4,
    img: "img/vegetable/vegetable-masala.png",
    quantity: 1,
  },
  {
    id: 29,
    name: "Veg Pakora",
    category: "vegetable",
    rating: 4.3,
    price: 4,
    img: "img/vegetable/vegetable-pakora.png",
    quantity: 1,
  },

  // Bánh Mì
  // {
  //   id: 30,
  //   name: "Momos",
  //   category: "bánh mì",
  //   rating: 4.3,
  //   price: 8,
  //   img: "img/BanhMi/cabbage-momos-.png",
  //   quantity: 1,
  // },
  {
    id: 31,
    name: "Bánh Mì Bò Lá Lốt",
    category: "bánh mì",
    rating: 4.3,
    price: 7,
    img: "img/BanhMi/BanhMiBoLaLot.png",
    quantity: 1,
  },
  {
    id: 32,
    name: "Bánh Mì Gà",
    category: "bánh mì",
    rating: 4.3,
    price: 5,
    img: "img/BanhMi/BanhMiGa.png",
    quantity: 1,
  },
  {
    id: 33,
    name: "Bánh Mì Heo Quay",
    category: "bánh mì",
    rating: 4.3,
    price: 16,
    img: "img/BanhMi/BanhMiHeoQuay.png",
    quantity: 1,
  },
  {
    id: 34,
    name: "Bánh Mì Thịt Chả",
    category: "bánh mì",
    rating: 4.3,
    price: 14,
    img: "img/BanhMi/BanhMiThitCha.png",
    quantity: 1,
  },
  {
    id: 35,
    name: "Bánh Mì Xíu Mại",
    category: "bánh mì",
    rating: 4.3,
    price: 10,
    img: "img/BanhMi/BanhMiXiuMai.png",
    quantity: 1,
  },
  {
    id: 36,
    name: "Bánh Mì Xúc Xích",
    category: "bánh mì",
    rating: 4.3,
    price: 8,
    img: "img/BanhMi/BanhMiXucXich.png",
    quantity: 1,
  },

  // Đồ Ăn Chay
  // {
  //   id: 37,
  //   name: "Butter Masala Dosa",
  //   category: "đồ ăn chay",
  //   rating: 4.3,
  //   price: 18,
  //   img: "img/DoAnChay/Butter-Masala-Dosa.png",
  //   quantity: 1,
  // },
  // {
  //   id: 38,
  //   name: "Idli",
  //   category: "đồ ăn chay",
  //   rating: 4.3,
  //   price: 20,
  //   img: "img/DoAnChay/idli-with-rice-flour.png",
  //   quantity: 1,
  // },
  {
    id: 39,
    name: "Bánh Xèo Chay",
    category: "đồ ăn chay",
    rating: 4.3,
    price: 12,
    img: "img/DoAnChay/BanhXeoChay.png",
    quantity: 1,
  },
  {
    id: 40,
    name: "Chả Giò Chay",
    category: "đồ ăn chay",
    rating: 4.3,
    price: 10,
    img: "img/DoAnChay/ChaGioChay.png",
    quantity: 1,
  },
  {
    id: 41,
    name: "Đậu Phụ Chiên",
    category: "đồ ăn chay",
    rating: 4.3,
    price: 15,
    img: "img/DoAnChay/DauPhuChien.png",
    quantity: 1,
  },
  {
    id: 42,
    name: "Gỏi Cuốn Chay",
    category: "đồ ăn chay",
    rating: 4.3,
    price: 40,
    img: "img/DoAnChay/GoiCuonChay.png",
    quantity: 1,
  },
  {
    id: 43,
    name: "Khoai Tây Nghiền Salad",
    category: "đồ ăn chay",
    rating: 4.3,
    price: 25,
    img: "img/DoAnChay/KhoaiTayNghienSalad.png",
    quantity: 1,
  },
  {
    id: 44,
    name: "Màn Thầu",
    category: "đồ ăn chay",
    rating: 4.3,
    price: 34,
    img: "img/DoAnChay/ManThau.png",
    quantity: 1,
  },
];

export { foodItem };
