const foodItem = [
  {
    id: 1,
    name: "Phở Tái Nạm",
    category: "Pho",
    rating: 4.3,
    price: 13,
    img: "images/biryani/OIP__2_-removebg-preview.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "Hyderabadi Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "images/biryani/Chicken-Biryani-hyd.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Egg Biryani",
    category: "biryani",
    rating: 4.3,
    price: 18,
    img: "images/biryani/egg-biryani.jpeg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Goan Fish Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "images/biryani/goan-fish-biryani.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "Mutton Biryani",
    category: "biryani",
    rating: 4.3,
    price: 10,
    img: "images/biryani/hyd-Mutton-Biryani.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "Kamrupi Biryani",
    category: "biryani",
    rating: 4.3,
    price: 12,
    img: "images/biryani/kamrupi-biryani.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Kashmiri Biryani",
    category: "biryani",
    rating: 4.3,
    price: 13,
    img: "images/biryani/kashmiri.pulao.jpg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Memoni Biryani",
    category: "biryani",
    rating: 4.3,
    price: 20,
    img: "images/biryani/memonibiryani.png",
    quantity: 1,
  },
  {
    id: 9,
    name: "Mughlai Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "images/biryani/mughlai-biryani.jpg",
    quantity: 1,
  },
  {
    id: 10,
    name: "Chicken Roast",
    category: "chicken",
    rating: 4.3,
    price: 11,
    img: "images/biryani/hutieukho-16-1440x960-removebg-preview.png",
    quantity: 1,
  },
  {
    id: 11,
    name: "Chicken Curry",
    category: "chicken",
    rating: 4.3,
    price: 10,
    img: "images/chicken/Chicken-Curry.jpg",
    quantity: 1,
  },
  {
    id: 12,
    name: "Chicken Do Pyaza",
    category: "chicken",
    rating: 4.3,
    price: 14,
    img: "images/chicken/Chicken-do-Pyaza.jpg",
    quantity: 1,
  },
  {
    id: 13,
    name: "Chicken Masala",
    category: "chicken",
    rating: 4.3,
    price: 12,
    img: "images/chicken/Chicken-Masala.jpeg",
    quantity: 1,
  },
  {
    id: 14,
    name: "Handi Chicken",
    category: "chicken",
    rating: 4.3,
    price: 17,
    img: "images/chicken/Handi-chicken.jpg",
    quantity: 1,
  },
  {
    id: 15,
    name: "Murgh Musallam",
    category: "chicken",
    rating: 4.3,
    price: 20,
    img: "images/chicken/Murgh-Musallam.jpg",
    quantity: 1,
  },
  {
    id: 17,
    name: "Hủ Tiếu Bò Viên",
    category: "Hủ Tiếu",
    rating: 4.3,
    price: 10,
    img: "images/hutieu/hutieubovien.png",
    quantity: 1,
  },
  {
    id: 18,
    name: "Hủ Tiếu Bò Kho",
    category: "Hủ Tiếu",
    rating: 4.3,
    price: 15,
    img: "images/hutieu/hutieubokho.png",
    quantity: 1,
  },
  {
    id: 19,
    name: "Hủ Tiếu Giò Heo",
    category: "Hủ Tiếu",
    rating: 4.3,
    price: 12,
    img: "images/hutieu/hutieugioheo.png",
    quantity: 1,
  },
  {
    id: 20,
    name: "Hủ Tiếu Thịt",
    category: "Hủ Tiếu",
    rating: 4.3,
    price: 8,
    img: "images/hutieu/hutieuthit.png",
    quantity: 1,
  },
  {
    id: 21,
    name: "Hủ Tiếu Xương",
    category: "Hủ Tiếu",
    rating: 4.3,
    price: 7,
    img: "images/hutieu/hutieuxuong.png",
    quantity: 1,
  },

  {
    id: 16,
    name: "Hủ Tiếu KHô",
    category: "Hủ Tiếu",
    rating: 4.3,
    price: 15,
    img: "images/hutieu/hutieukho.png",
    quantity: 1,
  },

  {
    id: 23,
    name: "Mì Khô",
    category: "Mì",
    rating: 4.3,
    price: 8,
    img: "images/mi/mikho.png",
    quantity: 1,
  },
  {
    id: 24,
    name: "Mì Xá Xíu",
    category: "Mì",
    rating: 4.3,
    price: 7,
    img: "images/mi/mixaxiu.jpg",
    quantity: 1,
  },
  {
    id: 25,
    name: "Mì Trứng",
    category: "Mì",
    rating: 4.3,
    price: 5,
    img: "images/mi/mitrung.png",
    quantity: 1,
  },
  {
    id: 26,
    name: "Mì Xương",
    category: "Mì",
    rating: 4.3,
    price: 7,
    img: "images/mi/mixuong.png",
    quantity: 1,
  },
  {
    id: 27,
    name: "Mì Bò Viên",
    category: "Mì",
    rating: 4.3,
    price: 10,
    img: "images/mi/mibovien.png",
    quantity: 1,
  },
  {
    id: 28,
    name: "Mì Xào Hải Sản",
    category: "Mì",
    rating: 4.3,
    price: 4,
    img: "images/mi/mixaohaisan.png",
    quantity: 1,
  },
  {
    id: 30,
    name: "Momos",
    category: "chinese",
    rating: 4.3,
    price: 8,
    img: "images/chinese/cabbage-momos-.jpg",
    quantity: 1,
  },
  {
    id: 31,
    name: "Chicken Manchurian",
    category: "chinese",
    rating: 4.3,
    price: 7,
    img: "images/chinese/ChickenManchurian.jpg",
    quantity: 1,
  },
  {
    id: 32,
    name: "Chili Chicken",
    category: "chinese",
    rating: 4.3,
    price: 5,
    img: "images/chinese/Chili-Chicken.jpg",
    quantity: 1,
  },
  {
    id: 33,
    name: "Chowmein",
    category: "chinese",
    rating: 4.3,
    price: 16,
    img: "images/chinese/chowmin.jpg",
    quantity: 1,
  },
  {
    id: 34,
    name: "Spring Roll",
    category: "chinese",
    rating: 4.3,
    price: 14,
    img: "images/chinese/spring-rolls.jpg",
    quantity: 1,
  },
  {
    id: 35,
    name: "Szechuan Chicken",
    category: "chinese",
    rating: 4.3,
    price: 10,
    img: "images/chinese/szechuan-chicken.jpg",
    quantity: 1,
  },
  {
    id: 36,
    name: "Fried Rice",
    category: "chinese",
    rating: 4.3,
    price: 8,
    img: "images/chinese/veg-fried-rice.jpg",
    quantity: 1,
  },
  {
    id: 37,
    name: "Butter Masala Dosa",
    category: "south indian",
    rating: 4.3,
    price: 18,
    img: "images/south indian/Butter-Masala-Dosa.png",
    quantity: 1,
  },
  {
    id: 38,
    name: "Idli",
    category: "south indian",
    rating: 4.3,
    price: 20,
    img: "images/south indian/idli-with-rice-flour.jpg",
    quantity: 1,
  },
  {
    id: 39,
    name: "Masala Dosa",
    category: "south indian",
    rating: 4.3,
    price: 12,
    img: "images/south indian/masala-dosa.jpg",
    quantity: 1,
  },
  {
    id: 40,
    name: "Mysore Bonda",
    category: "south indian",
    rating: 4.3,
    price: 10,
    img: "images/south indian/mysore-bonda.jpg",
    quantity: 1,
  },
  {
    id: 41,
    name: "Onion Uttapam",
    category: "south indian",
    rating: 4.3,
    price: 15,
    img: "images/south indian/onion-uttapam.jpg",
    quantity: 1,
  },
  {
    id: 42,
    name: "Plain Dosa",
    category: "south indian",
    rating: 4.3,
    price: 40,
    img: "images/south indian/plain-dosa.jpeg",
    quantity: 1,
  },
  {
    id: 43,
    name: "Rava Uttapam",
    category: "south indian",
    rating: 4.3,
    price: 25,
    img: "images/south indian/Rava-Uttapam.jpg",
    quantity: 1,
  },
  {
    id: 44,
    name: "Sambhar Vada",
    category: "south indian",
    rating: 4.3,
    price: 34,
    img: "images/south indian/sambhar-vada.jpg",
    quantity: 1,
  },
];

export { foodItem };
