const foodItem = [
{
  name: 'Phở Bò',
  category: 'phở',
  rating: 4.3,
  price: 13,
  img: 'img/Pho/PhoBo.png',
},
{
  name: 'Phở Bò',
  category: 'phở',
  rating: 4.3,
  price: 13,
  img: 'img/Pho/PhoBo.png',
},
{
  name: 'Phở Bò Gân',
  category: 'phở',
  rating: 4.3,
  price: 15,
  img: 'img/Pho/PhoBoGan.png',
},
{
  name: 'Phở Bò Viên',
  category: 'phở',
  rating: 4.3,
  price: 18,
  img: 'img/Pho/PhoBoVien.png',
},
{
  name: 'Phở Gà',
  category: 'phở',
  rating: 4.3,
  price: 15,
  img: 'img/Pho/PhoGa.png',
},
{
  name: 'Phở Heo',
  category: 'phở',
  rating: 4.3,
  price: 10,
  img: 'img/Pho/PhoHeo.png',
},
{
  name: 'Phở Tái Nạm',
  category: 'phở',
  rating: 4.3,
  price: 12,
  img: 'img/Pho/PhoTaiNam.png',
},
{
  name: 'Cơm bò bít tết',
  category: 'cơm',
  rating: 4.3,
  price: 11,
  img: 'img/Com/ComBoBitTet.png',
},
{
  name: 'Cơm Cà Ri',
  category: 'cơm',
  rating: 4.3,
  price: 10,
  img: 'img/Com/ComCaRi.png',
},
{
  name: 'Cơm Chiên Dương Châu',
  category: 'cơm',
  rating: 4.3,
  price: 14,
  img: 'img/Com/ComChienDuongChau.png',
},
{
  name: 'Cơm Gà Xối Mỡ',
  category: 'cơm',
  rating: 4.3,
  price: 12,
  img: 'img/Com/ComGaXoiMo.png',
},
{
  name: 'Cơm Sườn',
  category: 'cơm',
  rating: 4.3,
  price: 17,
  img: 'img/Com/ComSuon.png',
},
{
  name: 'Cơm Xá Xíu',
  category: 'cơm',
  rating: 4.3,
  price: 20,
  img: 'img/Com/ComXaXiu.png',
},
{
  name: 'Hủ Tiếu Bò Viên',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 10,
  img: 'img/hutieu/hutieubovien.png',
},
{
  name: 'Hủ Tiếu Bò Kho',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 15,
  img: 'img/hutieu/hutieubokho.png',
},
{
  name: 'Hủ Tiếu Giò Heo',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 12,
  img: 'img/hutieu/hutieugioheo.png',
},
{
  name: 'Hủ Tiếu Thịt',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 8,
  img: 'img/hutieu/hutieuthit.png',
},
{
  name: 'Hủ Tiếu Xương',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 7,
  img: 'img/hutieu/hutieuxuong.png',
},
{
  name: 'Hủ Tiếu KHô',
  category: 'hủ tiếu',
  rating: 4.3,
  price: 15,
  img: 'img/hutieu/hutieukho.png',
},
{
  name: 'Mì Khô',
  category: 'mì',
  rating: 4.3,
  price: 8,
  img: 'img/mi/mikho.png',
},
{
  name: 'Mì Xá Xíu',
  category: 'mì',
  rating: 4.3,
  price: 7,
  img: 'img/mi/mixaxiu.jpg',
},
{
  name: 'Mì Trứng',
  category: 'mì',
  rating: 4.3,
  price: 5,
  img: 'img/mi/mitrung.png',
},
{
  name: 'Mì Xương',
  category: 'mì',
  rating: 4.3,
  price: 7,
  img: 'img/mi/mixuong.png',
},
{
  name: 'Mì Bò Viên',
  category: 'mì',
  rating: 4.3,
  price: 10,
  img: 'img/mi/mibovien.png',
},
{
  name: 'Mì Xào Hải Sản',
  category: 'mì',
  rating: 4.3,
  price: 4,
  img: 'img/mi/mixaohaisan.png',
},
{
  name: 'Bánh Mì Bò Lá Lốt',
  category: 'bánh mì',
  rating: 4.3,
  price: 7,
  img: 'img/BanhMi/BanhMiBoLaLot.png',
},
{
  name: 'Bánh Mì Gà',
  category: 'bánh mì',
  rating: 4.3,
  price: 5,
  img: 'img/BanhMi/BanhMiGa.png',
},
{
  name: 'Bánh Mì Heo Quay',
  category: 'bánh mì',
  rating: 4.3,
  price: 16,
  img: 'img/BanhMi/BanhMiHeoQuay.png',
},
{
  name: 'Bánh Mì Thịt Chả',
  category: 'bánh mì',
  rating: 4.3,
  price: 14,
  img: 'img/BanhMi/BanhMiThitCha.png',
},
{
  name: 'Bánh Mì Xíu Mại',
  category: 'bánh mì',
  rating: 4.3,
  price: 10,
  img: 'img/BanhMi/BanhMiXiuMai.png',
},
{
  name: 'Bánh Mì Xúc Xích',
  category: 'bánh mì',
  rating: 4.3,
  price: 8,
  img: 'img/BanhMi/BanhMiXucXich.png',
},
{
  name: 'Bánh Xèo Chay',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 12,
  img: 'img/DoAnChay/BanhXeoChay.png',
},
{
  name: 'Chả Giò Chay',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 10,
  img: 'img/DoAnChay/ChaGioChay.png',
},
{
  name: 'Đậu Phụ Chiên',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 15,
  img: 'img/DoAnChay/DauPhuChien.png',
},
{
  name: 'Gỏi Cuốn Chay',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 40,
  img: 'img/DoAnChay/GoiCuonChay.png',
},
{
  name: 'Khoai Tây Nghiền Salad',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 25,
  img: 'img/DoAnChay/KhoaiTayNghienSalad.png',
},
{
  name: 'Màn Thầu',
  category: 'đồ ăn chay',
  rating: 4.3,
  price: 34,
  img: 'img/DoAnChay/ManThau.png',
},
{
  name: 'Phở nướng',
  category: 'phở',
  rating: 4.3,
  price: 20,
  img: 'img/phở/mibovien.png',
},
];
export { foodItem };